### ISSUE TITLE
[BUG] NameError: name 'write_parsing_response_buffer' is not defined

### ISSUE THREAD

**Issue by Links2004** [thelastWallE/OctoprintKlipperPlugin#59]
About your environment:
- Debian buster on RPI3
- OctoPrint: 1.6.1 
- OctoKlipper: 0.3.8.2

Started print and I am seeing this in the log:
printing is still working but the messages sound bad.

```
NameError: name 'write_parsing_response_buffer' is not defined
2021-05-25 08:56:51,319 - octoprint.util.comm - ERROR - Error while processing hook klipper:
Traceback (most recent call last):
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/util/comm.py", line 3903, in _readline
    ret = hook(self, ret)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint_klipper/__init__.py", line 389, in on_parse_gcode
    write_parsing_response_buffer()
NameError: name 'write_parsing_response_buffer' is not defined
2021-05-25 08:56:56,043 - octoprint.util.comm - ERROR - Error while processing hook klipper:
Traceback (most recent call last):
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/util/comm.py", line 3903, in _readline
    ret = hook(self, ret)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint_klipper/__init__.py", line 389, in on_parse_gcode
    write_parsing_response_buffer()
NameError: name 'write_parsing_response_buffer' is not defined
2021-05-25 08:57:00,827 - octoprint.util.comm - ERROR - Error while processing hook klipper:
Traceback (most recent call last):
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/util/comm.py", line 3903, in _readline
    ret = hook(self, ret)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/Octoprint/venv/lib/python3.7/site-packages/octoprint_klipper/__init__.py", line 389, in on_parse_gcode
    write_parsing_response_buffer()
NameError: name 'write_parsing_response_buffer' is not defined
```

**Comment by thelastWallE** [comment]
fixed in 0.3.8.3
